name: KitPreview
version: 2.4
main: me.enzol.kitspreview.KitsPreview
api-version: 1.16
load: POSTWORLD
author: EnzoL_
depend:
  - Essentials
commands:
  kitpreview:
    aliases: [previewkit]
  kiteditpreview:
    aliases: [editpreview]